#!/bin/bash
DRY_RUN=0
function printHelp {
  echo "Utility to run games and applications in separate X on discrete Nvidia graphic card"
  echo "Usage: "
  echo "nvidia-xrun [<options>] <app>"
  echo "Options: "
  echo "  -d    Dry run - prints the final command but does not execute it"
}

function execute {
  if [ $DRY_RUN -eq 1 ]
    then
    echo ">>Dry run. Command: $*"
  else
    eval $*
  fi
}


if [[ $EUID -eq 0 ]]; then
   echo "This script must not be run as root" >&2
   exit 1
fi

if [ "$1" == "-d" ]
  then
    DRY_RUN=1
    shift 1
fi

if [ $# -eq 0 ]
  then
    printHelp
    exit 1
fi

# calculate current VT
LVT=`sudo fgconsole`

# calculate first usable display
XNUM="-1"
SOCK="something"
while [ ! -z "$SOCK" ]
do
  XNUM=$(( $XNUM + 1 ))
  SOCK=$(ls -A -1 /tmp/.X11-unix | grep "X$XNUM" )
done
NEWDISP=":$XNUM"

if [ ! -z "$*" ] # generate exec line if arguments are given
then
  # test if executable exists
  if [ ! -x "$(which $1 2> /dev/null)" ]
  then
    echo "$1: No such executable!"
    exit 1
  fi
  # generate exec line
  EXECL="$(which $1)"
  shift 1
  EXECL="$EXECL $*"
  EXECPH=""
else # prepare to start new X sessions if no arguments passed
  EXECL=""
  EXECPH="New X session"
fi

EXECL="/etc/X11/xinit/nvidia-xinitrc $EXECL"

COMMAND="startx $EXECL -- $NEWDISP vt$LVT -background none -noreset -keeptty -verbose 7 -config nvidia-xorg.conf"

echo "Configuring Xorg to use root as nvidia doesn't have kms"
execute "sudo sed -i s/=no/=yes/g /etc/X11/Xwrapper.config"
echo 'Setting glx for nvidia'
execute "sudo update-alternatives --set glx /usr/lib/nvidia"
echo 'Waking up nvidia GPU'
execute "sudo tee /proc/acpi/bbswitch <<<ON"
echo 'Loading nvidia module'
execute "sudo modprobe nvidia"
execute "sudo modprobe nvidia_drm"
execute $COMMAND
echo 'Unloading nvidia module'
execute "sudo rmmod nvidia_drm nvidia_modeset nvidia"
echo 'Turning off nvidia GPU'
execute "sudo tee /proc/acpi/bbswitch <<<OFF"
echo 'Setting glx for intel/bumblebee'
execute "sudo update-alternatives --set glx /usr/lib/nvidia/bumblebee"
echo "Resetting Xorg for non-root login"
execute "sudo sed -i s/=yes/=no/g /etc/X11/Xwrapper.config"
